spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: postgres
    password: 1qaz!QAZ
    driver-class-name: org.postgresql.Driver

  jackson:
    time-zone: UTC

server:
  port: 8080
